### ISSUE TITLE
param.sh is not tracked?

### ISSUE THREAD

**Issue by MichaelChirico** [tdhock/data.table-revdeps#24]
https://github.com/tdhock/data.table-revdeps/blob/a9beda541ebfe8a648a3dfb8451f0a4620746027/README.org?plain=1#L20

Should this be checked in to this repo?

**Comment by tdhock** [comment]
no, it is generated automatically from https://github.com/tdhock/data.table-revdeps/blob/master/params.R#L319 I will add that to the README
