### ISSUE TITLE
Include short commit message for dev version?

### ISSUE THREAD

**Issue by MichaelChirico** [tdhock/data.table-revdeps#4]
One "nice-to-have" at the top of the report would be a short commit summary for the `master` commit.

Now I find we have to jump back and forth between the analysis page and the repo comparing hex digits, somewhat tedious. I had a look at the code but didn't quite follow where the commit hash is coming from. But `git log --pretty=format:"%h - %s"` will be helpful.

**Comment by tdhock** [comment]
hi Michael thanks for the suggestion. 
The commit hash is coming from params.R which is doing the git pull for most recent data.table master, then R CMD build. I added your suggested git log pretty to that script, so hopefully that output should be helpful in future revdep reports, https://github.com/tdhock/data.table-revdeps/commit/4f7d52242a26b3e3addf801e736c94c411825c31

**Comment by tdhock** [comment]
looks like this is working, with a message as below on most recent check, 
```
## data.table master is 4bc10a64 - Update/modernize CONTRIBUTING guide (#5863)
```
